title: Adeus Documentation
description: Open Source AI Wearable device
theme: just-the-docs

url: https://docs.adeus.ai

aux_links:
  Github: https://github.com/adamcohenhillel/ADeus

aux_links_new_tab: true

nav_external_links:
  - title: Join Us on Discord
    url: https://discord.gg/N5c6KXBgWW
    opens_in_new_tab: true

  - title: Adeus on GitHub
    url: https://github.com/adamcohenhillel/ADeus
    opens_in_new_tab: true
